<?php echo $this->breadCrumb(); ?>
                    
			<div style='float: left'>
                                <form id='loginform' class="form-horizontal" method='post' action='<?php echo $this->url(array('controller' => 'index', 'action' => 'login'), 'default', false); ?>'>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputName">Name</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputName" placeholder="Name">
			                    		</div>
			                    	</div>
			                        <div class="control-group">
			                    		<label class="control-label" for="inputSurname">Surname</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputSurname" placeholder="Surname">
			                    		</div>
			                    	</div>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputOrganization">Organization</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputOrganization" placeholder="Organization">
			                    		</div>
			                    	</div>
			                        <div class="control-group">
			                    		<label class="control-label" for="inputCountry">Country</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputCountry" placeholder="Country">
			                    		</div>
			                    	</div>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputCourseEnrolled">Course Enrolled</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputCourseEnrolled" placeholder="Course Enrolled">
			                    		</div>
			                    	</div>
			                        <div class="control-group">
			                    		<label class="control-label" for="inputEnrollDate">Enrollment Date</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputEnrollDate" placeholder="Enrollment Date">
			                    		</div>
			                    	</div>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputTelephone">Tel</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputTelephone" placeholder="Tel">
			                    		</div>
			                    	</div>
			                        <div class="control-group">
			                    		<label class="control-label" for="inputSkypeId">Skype Id</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputSkypeId" placeholder="Skype Id">
			                    		</div>
			                    	</div>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputEmail">Email</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputEmail" placeholder="Email">
			                    		</div>
			                    	</div>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputAdvisor">Advisor</label>
			                    		<div class="controls">
			                    			<input type="text" id="inputAdvisor" placeholder="Advisor">
			                    		</div>
			                    	</div>
			                    	
			                    	
			                        <div class="form-actions">
                        				<button id='btnsubmit' type="submit" class="btn btn-primary">Login</button>
                        				<button id='btncancel' type="button" class="btn">Cancel</button>                        
                        			</div>
                    		</form>
                 </div> 
                 
                 <div style='float: left; width: 50px;'>&nbsp;</div>
                 	
                  <div style='float: left;'>
                 
                 		<div style='width: 300px; height: 300px; border: 1px solid black;'></div>
                 		
                 </div>
<script type='text/javascript'>
	$(document).ready(function (e) {

		$('#btnsubmit').click(function (e) {
			$('#loginform').submit();
		});

		$('#btncancel').click(function (e) {
			$('#inputEmail').val('');
			$('#inputPassword').val('');

		});

	})
</script>                    