<table>
<tr>
	<td>To:</td>
	<td>
		<select name="to" id="to">
			<?php foreach ($this->users as $user) { ?>
				<option value="<?php echo $user->id; ?>"><?php echo $user->name; ?></option>
			<?php } ?>
		</select>
	</td>
</tr>
<tr>
	<td>Message</td>
	<td>
		<textarea id="reply"></textarea>
	</td>
</tr>
<tr>
	<td colspan="2"><button type="button" id="btnsend"><span>Send</span></button></td>
</tr>
</table>

<script type="text/javascript">
	$(document).ready(function (e) {
		$("#btnsend").click(function (e) {
             e.preventDefault();
             var data = { "message" : $("#reply").val(), 'to_user_id' : $("#to").val() };

             var options = {
                     url: "/message/send",
                     type: "post",
                     dataType: "json",
                     data: data,
                     success: function (json) {
                         $("#content").load("/index/home");
                     }
             };

             $.ajax(options);
		});
	});
</script>