<?php echo $this->breadCrumb($this->breadcrumb); ?>
                    
                    <div class="tabbable"> <!-- Only required for left/right tabs -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1" data-toggle="tab">Login</a></li>
                            <li><a href="#tab2" data-toggle="tab">Forgot Password</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                <form id='loginform' class="form-horizontal" method='post' action='<?php echo $this->url(array('controller' => 'index', 'action' => 'login'), 'default', false); ?>'>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputEmail">Email</label>
			                    		<div class="controls">
			                    			<input type="text" name="inputEmail" id="inputEmail" placeholder="Email">
			                    		</div>
			                    	</div>
			                        <div class="control-group">
			                            <label class="control-label" for="inputPassword">Password</label>
			                            <div class="controls">
			                            	<input type="password" name="inputPassword" id="inputPassword" placeholder="Password">
			                            </div>
			                        </div>
			                        <div class="form-actions">
                        				<button id='btnsubmit' type="submit" class="btn btn-primary">Login</button>
                        				<button id='btncancel' type="button" class="btn">Cancel</button>                        
                        			</div>
                    		</form>
                        
                            </div>
                            <div class="tab-pane" id="tab2">
                                <form id='passwordform' class="form-horizontal" method='post' action='<?php echo $this->url(array('controller' => 'index', 'action' => 'password'), 'default', false); ?>'>
			                    	<div class="control-group">
			                    		<label class="control-label" for="inputEmail">Email</label>
			                    		<div class="controls">
			                    			<input type="text" name="inputEmail" id="inputEmail" placeholder="Email">
			                    		</div>
			                    	</div>
			                        <div class="form-actions">
                        				<button id='btnsubmit' type="submit" class="btn btn-primary">Reset Password</button>
                        				<button id='btncancel' type="button" class="btn">Cancel</button>                        
                        			</div>
                    			</form>
                            </div>
                        </div>
                    </div>
                    
                   
                  
                    
                   
<script type='text/javascript'>
	$(document).ready(function (e) {

		$('#btnsubmit').click(function (e) {
			$('#loginform').submit();
		});

		$('#btncancel').click(function (e) {
			$('#inputEmail').val('');
			$('#inputPassword').val('');

		});

	})
</script>                    