<div class="row-fluid">
                  	<div class="pack">
                    <div class="navbar">
                    	<div class="row-fluid">
                        <div class="inner">
                        <h3>Registration </h3>
                        <ul class="registration">
                        				<li>
                        					<a href="/index/regform">Online Registration</a>
                        				</li>
                                    	<li>Course Fee <span> – 600 USD for Member Organization and 800 USD for Non-Member Organization (Member – Cooperatives, Savings and Credit Cooperatives, Savings and Credit Unions, Credit Unions is affiliated to National Federation)</span></li>
                                        <li>Payment Methods
                                        	<ul class="sub-list">
                                            	<li>Via bank transfer to ACCU bank account </li>
                                                <li>Via online payment method (tentative)</li>
                                            </ul>
                                         </li>
                                        <li>Cancellation and Refund Policies
                                        <ul class="sub-list">
                                            	<li class="bold">Cancellation Policy:<strong> There is no cancellation policy for ACUI. The course is offers for each individual learner with no registration period, hence you can enroll for the course you are interest whenever you feel ready to take the course</strong></li>
                                                <li class="bold">Refund Policy: <strong>If the learner would like to cancel their enrollment due to any difficulties in participating in the E-Learning program and the learner has not yet accessed the course. The cancellation shall be made in written to ACCU. In this case, learners can receive a refund with a deduction 100 USD for the administrative cost. If the cancellation is made after the learner has accessed the course, learner will not be able to obtain a refund.</strong></li>
                                            </ul>
                                        </li>
                                    </ul>
				
                    </div>
                            </div>
                        </div>
                    </div>
                  </div>