<ul class="breadcrumb">
                        <li><a href="#">Home</a> <span class="divider">/</span></li>
                        <li><a href="#">Library</a> <span class="divider">/</span></li>
                        <li class="active">Data</li>
                    </ul>
                    
                    <div class="tabbable"> <!-- Only required for left/right tabs -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1" data-toggle="tab">Section 1</a></li>
                            <li><a href="#tab2" data-toggle="tab">Section 2</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                <p>I'm in Section 1.</p>
                            </div>
                            <div class="tab-pane" id="tab2">
                                <p>Howdy, I'm in Section 2.</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="pagination">
                        <ul>
                            <li><a href="#">Prev</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">Next</a></li>
                        </ul>
                    </div>
                    
                    <ul class="pager">
                        <li class="previous">
                        <a href="#">&larr; Older</a>
                        </li>
                        <li class="next">
                        <a href="#">Newer &rarr;</a>
                        </li>
                    </ul>
                    
                    <div class="alert">
                    	<button type="button" class="close" data-dismiss="alert">&times;</button>
                    	<strong>Warning!</strong> Best check yo self, you're not looking too good.
                    </div>
                    
                    <div class="alert alert-error">
						<button type="button" class="close" data-dismiss="alert">x</button>
              			<strong>Oh snap!</strong> Change a few things up and try submitting again.
                    </div>
                    
                    <div class="alert alert-success">
                    	<button type="button" class="close" data-dismiss="alert">x</button>
                    	<strong>Well done!</strong> You successfully read this important alert message.
                    </div>
                    
                    <div class="alert alert-info">
                    	<button type="button" class="close" data-dismiss="alert">x</button>
                    	<strong>Heads up!</strong> This alert needs your attention, but it's not super important.
                    </div>
                    
                    <!-- Button to trigger modal -->
                    <a href="#myModal" role="button" class="btn btn-primary btn-large" data-toggle="modal">Launch demo modal</a><br><br>
                    
                    <!-- Modal -->
                    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    	<div class="modal-header">
                    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                    		<h3 id="myModalLabel">Modal header</h3>
                    	</div>
                    	<div class="modal-body">
                    		<p>One fine body…</p>
                    	</div>
                    	<div class="modal-footer">
                    		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    		<button class="btn btn-primary">Save changes</button>
                    	</div>
                    </div>
                    
                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Username</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Mark</td>
                                <td>Otto</td>
                                <td>@mdo</td>
                            </tr>
                            <tr class="info">
                                <td>2</td>
                                <td>Jacob</td>
                                <td>Thornton</td>
                                <td>@fat</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td colspan="2">Larry the Bird</td>
                                <td>@twitter</td>
                            </tr>
                        </tbody>
                    </table>
                    
                    <form class="form-horizontal">
                    	<div class="control-group">
                    		<label class="control-label" for="inputEmail">Email</label>
                    		<div class="controls">
                    			<input type="text" id="inputEmail" placeholder="Email">
                    		</div>
                    	</div>
                        <div class="control-group">
                            <label class="control-label" for="inputPassword">Password</label>
                            <div class="controls">
                            	<input type="password" id="inputPassword" placeholder="Password">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="inputTextarea">Text Area</label>
                            <div class="controls">
                            	<textarea rows="3"></textarea>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label" for="">Checkboxes</label>
                            <div class="controls">
                            	<label class="checkbox">
                                	<input type="checkbox" value="">
                                Option one is this and that—be sure to include why it's great
                                </label>
                            </div>
                            <div class="controls">
                            	<label class="radio">
                                	<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                                Option one is this and that—be sure to include why it's great
                                </label>
                            </div>
                            <div class="controls">
                            	<label class="radio">
                                	<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                                Option two can be something else and selecting it will deselect option one
                                </label>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label" for="">Inline Checkboxes</label>
                            <div class="controls">
                            	<label class="checkbox inline">
                                	<input type="checkbox" id="inlineCheckbox1" value="option1"> 1
                                </label>
                                <label class="checkbox inline">
                                	<input type="checkbox" id="inlineCheckbox1" value="option1"> 1
                                </label>
                                <label class="checkbox inline">
                                	<input type="checkbox" id="inlineCheckbox3" value="option3"> 3
                                </label>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label" for="">Select</label>
                            <div class="controls">
                                <select>
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="control-group warning">
                        	<label class="control-label" for="inputWarning">Input with warning</label>
                        	<div class="controls">
                        		<input type="text" id="inputWarning">
                        		<span class="help-inline">Something may have gone wrong</span>
                        	</div>
                        </div>
                         
                        <div class="control-group error">
                        	<label class="control-label" for="inputError">Input with error</label>
                        	<div class="controls">
                        		<input type="text" id="inputError">
                        		<span class="help-inline">Please correct the error</span>
                        	</div>
                        </div>
                         
                        <div class="control-group info">
                        	<label class="control-label" for="inputInfo">Input with info</label>
                        	<div class="controls">
                        		<input type="text" id="inputInfo">
                        		<span class="help-inline">Username is already taken</span>
                        	</div>
                        </div>
                         
                        <div class="control-group success">
                        	<label class="control-label" for="inputSuccess">Input with success</label>
                        	<div class="controls">
                        		<input type="text" id="inputSuccess">
                        		<span class="help-inline">Woohoo!</span>
                        	</div>
                        </div>
                        
                        
                            
    
                        
                        
                            
     
    
   
                        <div class="form-actions">
                        	<button type="submit" class="btn btn-primary">Save changes</button>
                        	<button type="button" class="btn">Cancel</button>
                            <button type="button" class="btn btn-info">Info</button>
                            <button type="button" class="btn btn-success">Success</button>
                            <button type="button" class="btn btn-warning">Warning</button>
                            <button type="button" class="btn btn-danger">Danger</button>
                            <button type="button" class="btn btn-inverse">Inverse</button>
                        </div>
                    </form>