<?php echo $this->breadCrumb($this->breadcrumb); ?>
                    
			
                                <form id='loginform' class="form-horizontal" method='post' action='<?php echo $this->url(array('controller' => 'course', 'action' => 'save'), 'default', false); ?>'>
			                    	
			                    	<div class="alert alert-success">
                    	<button type="button" class="close" data-dismiss="alert">x</button>
                    	<strong>Module Configure</strong> Click on Each Module to Configure the Module.
                    </div>			                    	
			                    	<?php foreach ($this->modules as $module) { ?>
				                    	<div class="control-group">
				                    		<a class='moduleconfig' module_id="<?php echo $module->id; ?>" href="#"><?php echo $module->module_name;?></a>
				                    	</div>
				                     <?php } ?>
<!-- 			                        <div class="form-actions"> -->
			                        	<input type="hidden" name="course_id" id="course_id" value="<?php echo $this->course_id; ?>" />
<!--                         				<button id='btnsubmit' type="submit" class="btn btn-primary">Next</button> -->
<!--                         				<button id='btncancel' type="button" class="btn">Cancel</button>                         -->
<!--                         			</div> -->
                    			</form>
                 
                 
<script type='text/javascript'>
	$(document).ready(function (e) {

		$('.moduleconfig').click(function (e) {
			var module_id = $(this).attr('module_id');
			var course_id = $("#course_id").val();
			$('#content').html('').load('/course/moduleconfig/course_id/' + course_id + '/module_id/' + module_id + '/');
			return false;
		});

		$('#btncancel').click(function (e) {

		});

	})
</script>                    