<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>ACUI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <meta property="og:title" content=""/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>

	<!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style>
	
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    
    <link href="/css/main-final.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="/assets/ico/favicon.png">

	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script src="http://malsup.github.io/min/jquery.form.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
    <script src="/js/doubletaptogo.js"></script>
    <script src="/js/jquery.validate.js"></script>
    <!-- jQuery ScrollTo Plugin -->
	<script src="//balupton.github.io/jquery-scrollto/lib/jquery-scrollto.js"></script>
	<!-- History.js -->
	<script src="//browserstate.github.io/history.js/scripts/bundled/html4+html5/jquery.history.js"></script>
	<!-- Ajaxify -->
	<script src="//raw.github.com/browserstate/ajaxify/master/ajaxify-html5.js"></script>
    <script type='text/javascript'>
    $(function() {

        // Prepare
        var History = window.History; // Note: We are using a capital H instead of a lower h
        if ( !History.enabled ) {
             // History.js is disabled for this browser.
             // This is because we can optionally choose to support HTML4 browsers or not.
            return false;
        }

        // Bind to StateChange Event
        History.Adapter.bind(window,'statechange',function() { // Note: We are using statechange instead of popstate
            var State = History.getState();
            $('#content').load(State.url);
        });        
    });
    </script>
</head>

<body>

<div class="wrapper">
	<div class="container">
    	<div class="row header">
        	<div class="span8"><img src="/images/logo.png" alt=""></div>
            <div class="span4">
            	<div class="btn-toolbar">
              		<div class="btn-group">
                		<button class="btn btn-primary dropdown-toggle pull-left" data-toggle="dropdown"><?php echo $this->name;?><span class="caret"></span></button>
                		<ul class="dropdown-menu">
                          <li><a id='achangepass' href="#">Change Password</a></li>
                          <li><a id='asendmessage' href="#">Personal Message</a></li>
                          <li class="divider"></li>
                          <li><a href="/index/logout">Logout</a></li>
                		</ul>
              		</div>                    
              	</div>
            </div>
            
            <hr>
       	</div>
    </div>
    
    
    <div class="container">
    	<div class="row">
    	
    		<?php echo $this->sideMenu(); ?>
    		
    		<img id="ajaxLoader" style='position: absolute;' src="/images/ajax-loader.gif" />
            <div id='content' class="span9 content-outer">
            	<?php echo $this->layout()->content ?>	
            </div>        
        </div>
    </div>
    
    <script type='text/javascript'>
		$(document).ready(function (e) {

			$('#ajaxLoader').hide();  // hide it initially
		    $(document).ajaxStart(function() {
		        $("#ajaxLoader").show();
		    });
		    $(document).ajaxStop(function() {
		        $("#ajaxLoader").hide();
		    });
		

			$.ajaxSetup ({
			    // Disable caching of AJAX responses
			    cache: false
			});
			
			$('#achangepass').click(function (e) {
				$('#content').html('').load('/profile/changepass');
			});
			$('#asendmessage').click(function (e) {
				$('#content').html('').load('/message/compose');
			});

			$(".breadcrumb").click(function (e) {
				$('#content').html('').load($(this).attr('data-url'));
			});
		});
    </script>    
</div>
</body>
</html>